### ISSUE TITLE
数据来源

### ISSUE THREAD

**Issue by zyp1573** [Azurlin/AnimalCrossingMC#1]
你好，看过项目后想使用vue重构自己用，发现图片是放在你的阿里云上的，想要一下道具的图片。还有我是刚刚玩动森，项目也很久没有更新过了，想知道diy有没有更新，想拿到最新的数据。

**Comment by Azurlin** [comment]
你好，目前DIY更新到人鱼系列啦（1.3.0版本更新后新增配方），如果你需要相关资源可以留下联系方式，或者联系邮箱Azurlin@outlook.com。

**Comment by zyp1573** [comment]
我的邮箱：zyp_1573@163.com  谢谢！

**Comment by Azurlin** [comment]
已发送，请查收~
